### ISSUE TITLE
Stop updating in realtime on the main branch

### ISSUE THREAD

**Issue by djack42** [jimboy3100/jimboy3100.github.io#1]
Could you please do the dev in another branch than the one used by the mod ?
Because in the meanwhile, the mod in malfunctionning for the enduser...

An idea would be to declare a flag in the url to specify the branch you want to use for the game and when the updates are stable enough on your side, to merge all the changes to the main branch.

I was trying to lod the game for the last 20 minutes and I end up here, looking at the commits every 2-5 minutes...

**Comment by jimboy3100** [comment]
Agario was down at the time, i always thought i found the solution. Normaly i make my tests elsewhere. I found no solution for today, will continue tommorow. LM doesnt work now.

**Comment by jimboy3100** [comment]
LM works again. Sorry for the inconvenience
