### ISSUE TITLE
slight freezing occurs when i start the game.

### ISSUE THREAD

**Issue by ghost** [jimboy3100/jimboy3100.github.io#12]
If i start or rejoin the game with account logged in, i experience slight freezing.
It does not occur if i connect to the server without account logged in.
https://i.imgur.com/ZNCxug7.gif
like this.
It's not in ogar, but only in legend mod.

I checked with chrome dev tool. I noticd that it happens during a connection with snez.org
<img src="https://i.imgur.com/4CXURv5.png">
Of course, if i block that element(https://lmsettings.snez.org/) with chrome dev tool, there will be no freezing. But this is a stopgap measure.

Please check it.

**Comment by jimboy3100** [comment]
My apologise for my late response.
wss://lmsettings.snez.org/ websocket  is used to find the banned users from Legend mod. It is also used to upload and download Theme settings. This needs 0.5 seconds for the websocket communication to be established. For some reason, you have 2 connections established
