### ISSUE TITLE
User tab is not showing

### ISSUE THREAD

**Issue by abdallahalaraby** [jimboy3100/jimboy3100.github.io#16]
I've seen the User tab in many screenshots but I've never been able to get it to show on my end.
I have the "Home" and then the "API" tab, there's no "User" tab in the middle!
I'm logged in with my Facebook account.
<img width="1440" alt="Screen Shot 2019-12-31 at 7 01 18 PM" src="https://user-images.githubusercontent.com/54676990/71628345-1dcfc800-2c00-11ea-8c2c-9ad23b645153.png">

**Comment by jimboy3100** [comment]
My apologise for my late response, API tab has the User tab info. LM is missing vanilla skin shop libraries.

**Comment by ghost** [comment]
No worries, but I'm not only talking about vanilla skins, what if I want to use my Mass and XP Boosts, what I'm currently doing is disable LM, enable mass or XP boost on agar.io, and then enable LM, is there an easier way to do this?
