### ISSUE TITLE
Question - Bot Target

### ISSUE THREAD

**Issue by AceTheGmodGeek** [jimboy3100/jimboy3100.github.io#17]
If I have Party Bots enabled, am I able to have my bots target another person? Also, what do each of the targeting buttons do on the top of the screen, and how do they work?
By targeting buttons, I mean this: https://i.gyazo.com/f918c233ff01fc5c84871affd5f4a77a.png

**Comment by jimboy3100** [comment]
"If I have Party Bots enabled, am I able to have my bots target another person?"
You cannot
"Also, what do each of the targeting buttons do on the top of the screen, and how do they work?"
You have to redefine the hotkeys of the bot commands on mod, see this video: https://www.youtube.com/watch?v=xIupgFR7ZTY
