### ISSUE TITLE
Old deals not working. 

### ISSUE THREAD

**Issue by AgarTbg** [jimboy3100/jimboy3100.github.io#2]
The purchase dialog never shows after clicking on the deal. Is this a bug or is it patched?

**Comment by jimboy3100** [comment]
Disable any Pop-Up blocker from Chrome
Old deals compatible with versions prior than 2.6
There have been cases that old deals brought only coins and not the actual skins
Use at your own risk
The miniclip library that old deals of mod are working is:
https://configs-web.agario.miniclippt.com/live/v9/1025/GameConfiguration.json
I have not updated it for the new library yet, I will try to make it auto updatable from miniclip
