### ISSUE TITLE
keyboard movement WASD support?

### ISSUE THREAD

**Issue by byanjiong** [jimboy3100/jimboy3100.github.io#20]
can add the WASD keyboard support? Or probably add simple example in user script gallery? I cant see any example on how to create a user script, some example is probably helpful... thanks... ^_^

**Comment by jimboy3100** [comment]
https://legendmod.ml/developers/index.html
For making a testing an own client. 
https://github.com/jimboy3100/jimboy3100.github.io/blob/master/ogario/ogario.v4.js
On this file you can see all basic commands, you can change them anytime.
Basic objkect on legend mod are: legendmod. and application.
By typing on console (F12, console) legendmod. you can see all attributes and functions on that object and store them.
If you want to create a tampermonkey scipt that works upon Legend mod, see this example: https://deltav4.glitch.me/private.user.js
