### ISSUE TITLE
Where is the old skin shop

### ISSUE THREAD

**Issue by Snithesh** [jimboy3100/jimboy3100.github.io#24]
I am unable to find the old skin can u help to find it,

**Comment by shap3e** [comment]
"comm4": "Enemy spotted at %currentSector%!",
		"comm5": "Need a teammate!",
		"comm6": "Tank the virus!",
		"comm7": "Eat the virus!",
		"comm8": "Let's bait!",
		"comm9": "Fake tricksplit!",
		"comm0": "Fuck!",
		"comm10": "Tricksplit!",
		"comm11": "Left!",
		"comm12": "Up!",
		"comm13": "Right!",
		"comm14": "Bottom!",
		"comm15": "Tricksplit!",
		"comm16": "Tricksplit!",
		"comm17": "",
		"comm18": "",
		"comm19": "",
		"comm20": "No!",
		"comm21": "Yes!",
		"comm22": "",
		"comm23": "Come!",
		"comm24": "CANON!",
		"comm25": "Wait!",
		"comm26": "Help Me!",
		"comm27": ""
	},
	"deltaHotkeys": {
		"hk-feed": "E",
		"hk-macroFeed": "W",
		"hk-split": "SPACE",
		"hk-doubleSplit": "Q",
		"hk-popSplit": "ALT+Q",
		"hk-tripleSplit": "",
		"hk-split16": "A",
		"hk-bots-split": "F",
		"hk-bots-feed": "T",
		"hk-bots-ai": "Z",
		"hk-pause": "R",
		"hk-switchPlayer": "TAB",
		"hk-quickResp": ""
",
		"hk-wave": "",
		"hk-autoResp": "",
		"hk-showMiniMap": ""
		"hk-hideChat": "H",
		"hk-clearChat": "C",
		"hk-chatMessage": "ENTER",
		"hk-showHUD": "
",
		"hk-showLb": "
",
		"hk-copyLb": "L",
		"hk-showTop5": "V",
		"hk-customMapTexture": "",
		"hk-undefined": "",
		"hk-switchCamera": "ALT+C",
		"hk-switchMarker": "ALT+B",
		"hk-switchMergeIndicator": ""
",
		"hk-showSplitRange": "U",
		"hk-showSplitInd": "I",
		"hk-showTeammatesInd": ""
",
		"hk-showOppColors": "O",
		"hk-toggleSkins": "",
		"hk-transparentSkins": "",
		"hk-showSkins": "S",
		"hk-showStats": ""
",
		"hk-toggleCells": "D",
		"hk-showFood": "X",
		"hk-showGrid": "G",
		"hk-toggleAutoZoom": "",
		"hk-resetZoom": ""
",
		"hk-showBgSectors": "B",
		"hk-showNames": "N",
		"hk-hideTeammatesNames": "",
		"hk-showMass": "M",
		"hk-zoom1": "ALT+1",
		"hk-zoom2": "ALT+2",
		"hk-zoom3": "ALT+3",
		"hk-zoom4": "ALT+4",
		"hk-zoom5": "ALT+5",
		"hk-comm1": "1",
		"hk-comm2": "2",
		"hk-comm3": "3",
		"hk-comm4": "4",
		"hk-comm5": "5",
		"hk-comm6": "6",
		"hk-comm7": "7",
		"hk-comm8": "8",
		"hk-comm9": "9",
		"hk-comm0": "0",
		"hk-comm10": "MOUSE WHEEL",
		"hk-comm11": "LEFT",
		"hk-comm12": "UP",
		"hk-comm13": "RIGHT",
		"hk-comm14": "DOWN",
		"hk-comm15": "MOUSE LEFT",
		"hk-comm16": "MOUSE RIGHT",
		"hk-comm17": "",
		"hk-comm20": "NUMPAD0",
		"hk-comm21": "NUMPAD1",
		"hk-comm22": "NUMPAD2",
		"hk-comm23": "NUMPAD3",
		"hk-comm24": "NUMPAD4",
		"hk-comm25": "NUMPAD5",
		"hk-comm26": "NUMPAD6",
		"hk-comm27": "NUMPAD7",
		"hk-comm18": "NUMPAD8",
		"hk-comm19": "NUMPAD9"
		},
	"ogarioPlayerProfiles": [
		{
			"nick": "ꞌRonald..!

",
			"clanTag": "",
			"skinURL": "https://i.imgur.com/hnC7agh.png",
			"color": "#3633A5"
		},
		{
			"nick": "ꞌRonald..!"

''",
			"clanTag": "",
			"skinURL": "https://i.imgur.com/rcETGWm.png",
			"color": "#3633A5"
		},
		{
			"nick": "ꞌRonald..!"

'",
			"clanTag": "",
			"skinURL": "https://i.imgur.com/hYEkQtb.png",
			"color": "#3633A5"
		},
		{
			"nick": "ꞌRonald..!"

",
			"clanTag": "",
			"skinURL": "https://i.imgur.com/V8IWSwo.png",
			"color": "#3633A5"
		},
		{
			"nick": "ꞌRonald..!"

",
			"clanTag": "",
			"skinURL": "https://i.imgur.com/uUUVnm8.jpeg",
			"color": "#3633A5"
		},
		{
			"nick": "ꞌRonald..!"

'",
			"clanTag": "",
			"skinURL": "https://i.imgur.com/b51xV3J.jpeg",
			"color": "#3633A5"
		},
		{
			"nick": "ꞌRonald..!"

",
			"clanTag": "",
			"skinURL": "https://i.imgur.com/KZkBibm.jpg",
			"color": "#3633A5"
		},
		{
			"nick": "ꞌRonald..!"

",
			"clanTag": "",
			"skinURL": "https://i.imgur.com/gD5C57d.png",
			"color": "#3633A5"
		},
		{
			"nick": "ꞌRonald..!"

",
			"clanTag": "",
			"skinURL": "https://i.imgur.com/AQBmwpN.png",
			"color": "#3633A5"
		},
		{
			"nick": "ꞌRonald..!"

",
			"clanTag": "",
			"skinURL": "https://i.imgur.com/mbaXYj0.jpg",
			"color": "#3633A5"
		},
		{
			"nick": "ꞌRonald..!"

",
			"clanTag": "",
			"skinURL": "https://i.imgur.com/vhmxGfQ.png",
			"color": "#3633A5"
		},
		{
			"nick": "ꞌRonald..!"

" Dz.!",
			"clanTag": "",
			"skinURL": "https://i.imgur.com/zoh2T6Z.png",
			"color": "#3633A5"
		},
		{
			"nick": "ꞌRonald..!"

",
			"clanTag": "",
			"skinURL": "https://i.imgur.com/7cugADY.png",
			"color": "#3633A5"
		},
		{
			"nick": "ꞌRonald..!"

",
			"clanTag": "",
			"skinURL": "https://i.imgur.com/AFU3i3j.png",
			"color": "#3633A5"
		},
		{
			"nick": "ꞌRonald..!"

",
			"clanTag": "",
			"skinURL": "https://i.imgur.com/SQ7e1bV.jpg",
			"color": "#3633A5"
		},
		{
			"nick": "ꞌRonald..!"

",
			"clanTag": "",
			"skinURL": "https://i.imgur.com/QBGrECu.jpg",
			"color": "#3633A5"
		},
		{
			"nick": "ꞌRonald..!"

",
			"clanTag": "",
			"skinURL": "https://i.imgur.com/5031OWW.png",
			"color": "#3633A5"
		},
		{
			"nick": "ꞌRonald..!"

",
			"clanTag": "",
			"skinURL": "https://i.imgur.com/hnC7agh.png",
			"color": "#3633A5"
		}
	],
	"ogarioSettings": {
		"animation": 140,
		"cameraDelay": 0,
		"centerWeightCamera": false,
		"autoZoom": false,
		"zo
