### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Gasvash** [jimboy3100/jimboy3100.github.io#9]
Hello, I admire your work, and your extensions for agario, I use legend but I would like to connect to a private server created with MultiOgar Edited through the console with
core.disableIntegrityChecks(true);
core.connect("ws://localhost:443");
but I get
 Uncaught TypeError: core.disableIntegrityChecks is not a function
    at <anonymous>:1:6

Can you configure for private server? Please

**Comment by jimboy3100** [comment]
There is not such function on Legend mod yet, but i will make some tests that may allow us to play on private servers.
